# Generated by Django 5.1.6 on 2025-03-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
