# Generated by Django 5.1.6 on 2025-03-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager_main', '0002_portfolio_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
