# Generated by Django 5.1.6 on 2025-03-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_manager_main', '0003_remove_contactmessage_subject_contactmessage_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
